import type {
  CounselorActionCode,
  CounselorPriority,
  CounselorRisk,
  CounselorRoutingTarget,
  CounselorStatus,
} from "../model/consultantWorkspaceTypes";

export interface MockBackendInquiryProjection {
  status: CounselorStatus;
  riskLevel: CounselorRisk;
  priority: CounselorPriority;
  routingTarget: CounselorRoutingTarget;
  routingReason: string;
  requiresConsultation: boolean;
  feedbackResolved: boolean;
  waitingMinutes: number;
  assignedCounselor: string;
  allowedActionCodes: readonly CounselorActionCode[];
}

/**
 * 상담 화면이 업무 규칙을 계산하지 않도록 Backend 응답 모양을 대신하는 Mock Snapshot이다.
 * 실제 API 연결 시 이 파일을 Remote DTO Mapper 결과로 교체하며, 화면에서는 값을 재계산하지 않는다.
 */
const MOCK_BACKEND_PROJECTION_BY_SCENARIO: Record<
  string,
  MockBackendInquiryProjection
> = {
  "SYN-JAC104-001": {
    status: "QUESTIONNAIRE_IN_PROGRESS",
    riskLevel: "CAUTION",
    priority: "HIGH",
    routingTarget: "CONSULTANT",
    routingReason: "주의 문의는 상담사가 안내 내용을 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 30,
    assignedCounselor: "미배정",
    allowedActionCodes: [],
  },
  "SYN-JAC104-002": {
    status: "RESOLVED",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 3270,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-003": {
    status: "RESOLVED",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 90,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-004": {
    status: "CONSULTATION_REQUIRED",
    riskLevel: "DANGER",
    priority: "URGENT",
    routingTarget: "CONSULTANT",
    routingReason: "긴급 문의는 상담사가 안전 안내를 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 60,
    assignedCounselor: "미배정",
    allowedActionCodes: ["START_CONSULTATION"],
  },
  "SYN-JAC104-005": {
    status: "RESOLVED",
    riskLevel: "CAUTION",
    priority: "HIGH",
    routingTarget: "CONSULTANT",
    routingReason: "주의 문의는 상담사가 안내 내용을 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 90,
    assignedCounselor: "미배정",
    allowedActionCodes: [],
  },
  "SYN-JAC104-006": {
    status: "CONSULTATION_REQUIRED",
    riskLevel: "DANGER",
    priority: "URGENT",
    routingTarget: "CONSULTANT",
    routingReason: "긴급 문의는 상담사가 안전 안내를 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 60,
    assignedCounselor: "미배정",
    allowedActionCodes: ["START_CONSULTATION"],
  },
  "SYN-JAC104-007": {
    status: "RESOLVED",
    riskLevel: "CAUTION",
    priority: "HIGH",
    routingTarget: "CONSULTANT",
    routingReason: "주의 문의는 상담사가 안내 내용을 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 90,
    assignedCounselor: "미배정",
    allowedActionCodes: [],
  },
  "SYN-JAC104-008": {
    status: "VISIT_REVIEW_PENDING",
    riskLevel: "CAUTION",
    priority: "HIGH",
    routingTarget: "CONSULTANT",
    routingReason: "주의 문의는 상담사가 안내 내용을 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 150,
    assignedCounselor: "한유진",
    allowedActionCodes: ["VISIT_NEEDED", "VISIT_NOT_NEEDED"],
  },
  "SYN-JAC104-009": {
    status: "RESOLVED",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 90,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-010": {
    status: "QUESTIONNAIRE_IN_PROGRESS",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 30,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-011": {
    status: "QUESTIONNAIRE_IN_PROGRESS",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 30,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-013": {
    status: "CONSULTATION_IN_PROGRESS",
    riskLevel: "DANGER",
    priority: "URGENT",
    routingTarget: "CONSULTANT",
    routingReason: "긴급 문의는 상담사가 안전 안내를 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 90,
    assignedCounselor: "한유진",
    allowedActionCodes: [
      "UPDATE_CONSULTATION_SUMMARY",
      "CONFIRM_CONSULTATION_SUMMARY",
      "CONSULTATION_COMPLETED",
      "VISIT_REVIEW_REQUIRED",
    ],
  },
  "SYN-JAC104-014": {
    status: "VISIT_SCHEDULED",
    riskLevel: "DANGER",
    priority: "URGENT",
    routingTarget: "CONSULTANT",
    routingReason: "긴급 문의는 상담사가 안전 안내를 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 180,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-015": {
    status: "QUESTIONNAIRE_IN_PROGRESS",
    riskLevel: "CAUTION",
    priority: "HIGH",
    routingTarget: "CONSULTANT",
    routingReason: "주의 문의는 상담사가 안내 내용을 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 30,
    assignedCounselor: "미배정",
    allowedActionCodes: [],
  },
  "SYN-JAC104-017": {
    status: "COMPLETION_PENDING",
    riskLevel: "DANGER",
    priority: "URGENT",
    routingTarget: "CONSULTANT",
    routingReason: "긴급 문의는 상담사가 안전 안내를 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: true,
    waitingMinutes: 120,
    assignedCounselor: "한유진",
    allowedActionCodes: ["FINALIZE_INQUIRY"],
  },
  "SYN-JAC104-018": {
    status: "COMPLETION_PENDING",
    riskLevel: "DANGER",
    priority: "URGENT",
    routingTarget: "CONSULTANT",
    routingReason: "긴급 문의는 상담사가 안전 안내를 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: true,
    waitingMinutes: 210,
    assignedCounselor: "미배정",
    allowedActionCodes: ["FINALIZE_INQUIRY"],
  },
  "SYN-JAC104-019": {
    status: "RESOLVED",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 90,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-020": {
    status: "QUESTIONNAIRE_IN_PROGRESS",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 30,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-021": {
    status: "RESOLVED",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 270,
    assignedCounselor: "방문기사 담당",
    allowedActionCodes: [],
  },
  "SYN-JAC104-022": {
    status: "VISIT_SCHEDULING",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 60,
    assignedCounselor: "방문기사 자동 인계",
    allowedActionCodes: [],
  },
  "SYN-JAC104-023": {
    status: "VISIT_SCHEDULING",
    riskLevel: "GENERAL",
    priority: "NORMAL",
    routingTarget: "FIELD_TECHNICIAN",
    routingReason: "일반 문의는 AI가 방문기사에게 자동 인계합니다.",
    requiresConsultation: false,
    feedbackResolved: false,
    waitingMinutes: 90,
    assignedCounselor: "방문기사 자동 인계",
    allowedActionCodes: [],
  },
  "SYN-JAC104-024": {
    status: "CONSULTATION_REQUIRED",
    riskLevel: "CAUTION",
    priority: "HIGH",
    routingTarget: "CONSULTANT",
    routingReason: "주의 문의는 상담사가 안내 내용을 먼저 확인합니다.",
    requiresConsultation: true,
    feedbackResolved: false,
    waitingMinutes: 60,
    assignedCounselor: "미배정",
    allowedActionCodes: ["START_CONSULTATION"],
  },
};

export function getMockBackendInquiryProjection(
  scenarioId: string,
): MockBackendInquiryProjection {
  const projection = MOCK_BACKEND_PROJECTION_BY_SCENARIO[scenarioId];
  if (!projection) {
    throw new Error(`Mock Backend Projection이 없습니다: ${scenarioId}`);
  }
  return projection;
}
