# Generated by Django 5.2.16 on 2026-07-27 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('customer_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNING', '기사 배정 중'), ('SCHEDULING', '일정 조율 중'), ('CONFIRMED', '방문 확정'), ('EN_ROUTE', '이동 중'), ('IN_PROGRESS', '방문 진행 중'), ('COMPLETED', '방문 완료'), ('FOLLOW_UP_REQUIRED', '추가 방문 필요'), ('CANCELLED', '취소')], default='ASSIGNING', max_length=30)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='inquiries.inquiry')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='visits.visitrequest')),
            ],
        ),
    ]
