"""API v0.3에 정의된 공통 오류 코드."""


INVALID_REQUEST = "INVALID_REQUEST"
AUTH_REQUIRED = "AUTH_REQUIRED"
FORBIDDEN = "FORBIDDEN"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
STATE_CONFLICT = "STATE-CONFLICT-01"
DUPLICATE_EVENT = "DUPLICATE-EVENT-01"

WORKFLOW_PUBLIC_CODE_BY_INTERNAL = {
    "STATE_VERSION_CONFLICT": STATE_CONFLICT,
    "IDEMPOTENCY_KEY_REUSE_CONFLICT": DUPLICATE_EVENT,
}
