"""API v0.3에 정의된 공통 오류 코드."""


INVALID_REQUEST = "INVALID_REQUEST"
AUTH_REQUIRED = "AUTH_REQUIRED"
FORBIDDEN = "FORBIDDEN"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
STATE_CONFLICT = "STATE-CONFLICT-01"
DUPLICATE_EVENT = "DUPLICATE-EVENT-01"
PRODUCT_NOT_SUPPORTED = "PRODUCT_NOT_SUPPORTED"
SUBSCRIPTION_ALREADY_ACTIVE = "SUBSCRIPTION_ALREADY_ACTIVE"
AI_GUIDANCE_NOT_READY = "AI_GUIDANCE_NOT_READY"
AI_HANDOFF_NOT_READY = "AI_HANDOFF_NOT_READY"
AI_HANDOFF_STALE = "AI_HANDOFF_STALE"
AI_HANDOFF_EVIDENCE_REJECTED = "AI_HANDOFF_EVIDENCE_REJECTED"
CONSULTATION_RESULT_NOT_READY = "CONSULTATION_RESULT_NOT_READY"
HUMAN_REVIEW_CONSULTATION_LOCKED = "HUMAN_REVIEW_CONSULTATION_LOCKED"

WORKFLOW_PUBLIC_CODE_BY_INTERNAL = {
    "STATE_VERSION_CONFLICT": STATE_CONFLICT,
    "IDEMPOTENCY_KEY_REUSE_CONFLICT": DUPLICATE_EVENT,
}
