# Generated by Django 5.2.16 on 2026-07-27 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('detected_text', models.TextField(blank=True)),
                ('risk_level', models.CharField(default='GENERAL', max_length=20)),
                ('usage_guidance_status', models.CharField(default='NORMAL', max_length=30)),
                ('state', models.CharField(choices=[('DRAFT', '작성 중'), ('QUESTIONNAIRE_IN_PROGRESS', '문진 진행 중'), ('AI_GUIDANCE', 'AI 안내'), ('CONSULTATION_REQUIRED', '상담 필요'), ('CONSULTATION_IN_PROGRESS', '상담 중'), ('VISIT_REVIEW_PENDING', '방문 검토'), ('VISIT_SCHEDULING', '방문 조율'), ('VISIT_SCHEDULED', '방문 예정'), ('COMPLETION_PENDING', '완료 확인 대기'), ('REVISIT_REQUIRED', '추가 방문 필요'), ('REOPENED', '문의 재개'), ('RESOLVED', '해결'), ('CANCELLED', '취소')], default='DRAFT', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=100)),
                ('chunk_id', models.CharField(blank=True, max_length=100)),
                ('document_id', models.CharField(max_length=120)),
                ('document_title', models.CharField(max_length=200)),
                ('document_version', models.CharField(max_length=50)),
                ('page_refs', models.JSONField(default=list)),
                ('evidence_summary', models.TextField()),
                ('verification_status', models.CharField(default='text_and_visual_verified', max_length=80)),
                ('source_landing_url', models.URLField(blank=True)),
                ('source_direct_download_url', models.URLField(blank=True)),
                ('product_code', models.CharField(default='WPUJAC104DWH', max_length=50)),
                ('manual_model', models.CharField(default='WPU-JAC104D', max_length=50)),
                ('scope_role', models.CharField(default='mvp_primary', max_length=50)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_cards', to='inquiries.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inquiries/%Y/%m/%d/')),
                ('image_type', models.CharField(default='CUSTOMER_SYMPTOM', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inquiries.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='WPUJAC104DWH', max_length=50)),
                ('manual_model', models.CharField(default='WPU-JAC104D', max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='inquiries.product'),
        ),
    ]
