# Generated by Django 5.2.16 on 2026-08-19 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0013_inquiry_priority_code'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notice_code', models.CharField(max_length=50, unique=True)),
                ('category_code', models.CharField(choices=[('EMERGENCY', '긴급'), ('EVENT', '이벤트'), ('SYSTEM', '시스템'), ('WORK', '근무'), ('WELFARE', '복지'), ('TRAINING', '교육')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('department_name', models.CharField(max_length=100)),
                ('published_on', models.DateField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_synthetic', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'operations_dashboard_notice',
                'indexes': [models.Index(fields=['is_published', 'published_on', 'display_order'], name='ix_ops_dashboard_notice')],
                'constraints': [models.CheckConstraint(condition=models.Q(('category_code__in', ['EMERGENCY', 'EVENT', 'SYSTEM', 'WORK', 'WELFARE', 'TRAINING'])), name='ck_ops_dashboard_notice_category'), models.CheckConstraint(condition=models.Q(('is_synthetic', True)), name='ck_ops_dashboard_notice_synthetic'), models.CheckConstraint(condition=models.Q(models.Q(('notice_code', ''), _negated=True), models.Q(('title', ''), _negated=True), models.Q(('body', ''), _negated=True), models.Q(('department_name', ''), _negated=True)), name='ck_ops_dashboard_notice_content')],
            },
        ),
        migrations.CreateModel(
            name='InquiryDashboardProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('warranty_ends_on', models.DateField(blank=True, null=True)),
                ('previous_visit_count', models.PositiveIntegerField(default=0)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('inquiry', models.OneToOneField(db_column='inquiry_id', on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_profile', to='inquiries.inquiry')),
            ],
            options={
                'db_table': 'operations_inquiry_dashboard_profile',
                'indexes': [models.Index(fields=['warranty_ends_on'], name='ix_ops_inquiry_warranty_end')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='ck_ops_inquiry_dashboard_title'), models.CheckConstraint(condition=models.Q(('is_synthetic', True)), name='ck_ops_inquiry_dashboard_synthetic')],
            },
        ),
        migrations.CreateModel(
            name='StaffDirectoryEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('staff_type', models.CharField(choices=[('CONSULTANT', 'Consultant'), ('TECHNICIAN', 'Technician')], max_length=20)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('position_title', models.CharField(blank=True, max_length=80)),
                ('extension_number', models.CharField(blank=True, max_length=30)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='staff_directory_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_staff_directory_entry',
                'indexes': [models.Index(fields=['staff_type', 'is_active', 'display_order'], name='ix_ops_staff_directory')],
                'constraints': [models.CheckConstraint(condition=models.Q(('staff_type__in', ['CONSULTANT', 'TECHNICIAN'])), name='ck_ops_staff_directory_type'), models.CheckConstraint(condition=models.Q(models.Q(('branch_name', ''), ('staff_type', 'CONSULTANT'), models.Q(('department_name', ''), _negated=True), models.Q(('position_title', ''), _negated=True), models.Q(('extension_number', ''), _negated=True)), models.Q(('department_name', ''), ('extension_number', ''), ('position_title', ''), ('staff_type', 'TECHNICIAN'), models.Q(('branch_name', ''), _negated=True)), _connector='OR'), name='ck_ops_staff_directory_shape')],
            },
        ),
    ]
