# Generated by Django 5.2.16 on 2026-07-30 11:35

import uuid

import apps.audit.models.ai_run
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("inquiries", "0005_inquiry_ux_inquiry_id_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "task_type_code",
                    models.CharField(
                        choices=[
                            (
                                "STRUCTURE_SYMPTOM",
                                "Structure symptom",
                            ),
                            (
                                "GENERATE_QUESTIONS",
                                "Generate questions",
                            ),
                            ("ASSESS_RISK", "Assess risk"),
                            (
                                "RETRIEVE_EVIDENCE",
                                "Retrieve evidence",
                            ),
                            (
                                "GENERATE_GUIDANCE",
                                "Generate guidance",
                            ),
                            (
                                "SUMMARIZE_CONSULTATION",
                                "Summarize consultation",
                            ),
                            ("DRAFT_HANDOFF", "Draft handoff"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "request_schema_version",
                    models.CharField(default="v1", max_length=30),
                ),
                (
                    "response_schema_version",
                    models.CharField(max_length=30),
                ),
                (
                    "model_provider",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "model_config_version",
                    models.CharField(default="v1", max_length=64),
                ),
                (
                    "model_config",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "input_payload",
                    models.JSONField(blank=True, default=dict),
                ),
                ("input_sha256", models.CharField(max_length=64)),
                (
                    "idempotency_key",
                    models.CharField(max_length=128),
                ),
                (
                    "raw_output_text",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "validated_output_payload",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "schema_validation_status_code",
                    models.CharField(
                        choices=[
                            ("NOT_RUN", "Not run"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_RUN",
                        max_length=40,
                    ),
                ),
                (
                    "schema_validation_errors",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("NO_EVIDENCE", "No evidence"),
                            ("FAILED", "Failed"),
                            ("TIMED_OUT", "Timed out"),
                            ("RETRYING", "Retrying"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=40,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "latency_ms",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "input_tokens",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "output_tokens",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True),
                ),
                ("retry_count", models.SmallIntegerField(default=0)),
                ("correlation_id", models.UUIDField()),
                (
                    "inquiry",
                    models.ForeignKey(
                        db_column="inquiry_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_runs",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
            options={
                "db_table": "aiops_ai_run",
                "indexes": [
                    models.Index(
                        fields=[
                            "inquiry",
                            "task_type_code",
                            "-created_at",
                        ],
                        name="ix_ai_run_inquiry_task",
                    ),
                    models.Index(
                        fields=["status_code", "created_at"],
                        name="ix_ai_run_status",
                    ),
                    models.Index(
                        fields=["correlation_id"],
                        name="ix_ai_run_correlation",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("idempotency_key",),
                        name="ux_ai_run_idempotency",
                    ),
                    models.UniqueConstraint(
                        fields=("id", "inquiry"),
                        name="ux_ai_run_id_inquiry",
                    ),
                    models.UniqueConstraint(
                        fields=("id", "inquiry", "correlation_id"),
                        name="ux_ai_run_id_inquiry_correlation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            apps.audit.models.ai_run.IsJSONArray(
                                models.F("schema_validation_errors")
                            )
                        ),
                        name="ck_ai_run_schema_errors_array",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status_code", "SUCCEEDED"),
                                _negated=True,
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                (
                                    "schema_validation_status_code",
                                    "PASSED",
                                ),
                                (
                                    "validated_output_payload__isnull",
                                    False,
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="ck_ai_run_success",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "status_code__in",
                                    ["FAILED", "TIMED_OUT"],
                                ),
                                _negated=True,
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("error_code__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_ai_run_failure",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("completed_at__isnull", True),
                            models.Q(
                                (
                                    "completed_at__gte",
                                    models.F("created_at"),
                                ),
                                ("started_at__isnull", True),
                                ("status_code", "CANCELLED"),
                            ),
                            models.Q(
                                (
                                    "completed_at__gte",
                                    models.F("started_at"),
                                ),
                                ("started_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_ai_run_time_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "input_sha256__regex",
                                "^[0-9a-f]{64}$",
                            )
                        ),
                        name="ck_ai_run_input_hash",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            apps.audit.models.ai_run.IsJSONObject(
                                models.F("model_config")
                            )
                        ),
                        name="ck_ai_run_model_config",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status_code", "NO_EVIDENCE"),
                                _negated=True,
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                (
                                    "schema_validation_status_code",
                                    "PASSED",
                                ),
                                (
                                    "validated_output_payload__isnull",
                                    False,
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="ck_ai_run_no_evidence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("retry_count__gte", 0),
                            models.Q(
                                ("latency_ms__isnull", True),
                                ("latency_ms__gte", 0),
                                _connector="OR",
                            ),
                            models.Q(
                                ("input_tokens__isnull", True),
                                ("input_tokens__gte", 0),
                                _connector="OR",
                            ),
                            models.Q(
                                ("output_tokens__isnull", True),
                                ("output_tokens__gte", 0),
                                _connector="OR",
                            ),
                        ),
                        name="ck_ai_run_nonnegative_metrics",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("started_at__isnull", True),
                                (
                                    "status_code__in",
                                    ["QUEUED", "CANCELLED"],
                                ),
                            ),
                            models.Q(
                                ("model_name__isnull", False),
                                ("model_provider__isnull", False),
                                ("prompt_version__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_ai_run_reproducibility",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("started_at__isnull", True),
                                ("status_code", "QUEUED"),
                            ),
                            models.Q(
                                ("completed_at__isnull", True),
                                ("started_at__isnull", False),
                                (
                                    "status_code__in",
                                    ["RUNNING", "RETRYING"],
                                ),
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("started_at__isnull", False),
                                (
                                    "status_code__in",
                                    [
                                        "SUCCEEDED",
                                        "NO_EVIDENCE",
                                        "FAILED",
                                        "TIMED_OUT",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("status_code", "CANCELLED"),
                            ),
                            _connector="OR",
                        ),
                        name="ck_ai_run_lifecycle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            apps.audit.models.ai_run.IsJSONObject(
                                models.F("input_payload")
                            ),
                            models.Q(
                                (
                                    "validated_output_payload__isnull",
                                    True,
                                ),
                                apps.audit.models.ai_run.IsJSONObject(
                                    models.F(
                                        "validated_output_payload"
                                    )
                                ),
                                _connector="OR",
                            ),
                        ),
                        name="ck_ai_run_json_objects",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "schema_validation_status_code",
                                    "FAILED",
                                ),
                                _negated=True,
                            ),
                            models.Q(
                                ("raw_output_text__isnull", False),
                                apps.audit.models.ai_run.IsNonEmptyJSONArray(
                                    models.F(
                                        "schema_validation_errors"
                                    )
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="ck_ai_run_schema_failure",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "task_type_code__in",
                                [
                                    "STRUCTURE_SYMPTOM",
                                    "GENERATE_QUESTIONS",
                                    "ASSESS_RISK",
                                    "RETRIEVE_EVIDENCE",
                                    "GENERATE_GUIDANCE",
                                    "SUMMARIZE_CONSULTATION",
                                    "DRAFT_HANDOFF",
                                ],
                            )
                        ),
                        name=(
                            "ck_aiops_ai_run_"
                            "task_type_code_allowed"
                        ),
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "schema_validation_status_code__in",
                                ["NOT_RUN", "PASSED", "FAILED"],
                            )
                        ),
                        name=(
                            "ck_aiops_ai_run_"
                            "schema_validation_status_code_allowed"
                        ),
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status_code__in",
                                [
                                    "QUEUED",
                                    "RUNNING",
                                    "SUCCEEDED",
                                    "NO_EVIDENCE",
                                    "FAILED",
                                    "TIMED_OUT",
                                    "RETRYING",
                                    "CANCELLED",
                                ],
                            )
                        ),
                        name=(
                            "ck_aiops_ai_run_status_code_allowed"
                        ),
                    ),
                ],
            },
        ),
    ]
