# Generated by Django 5.2.16 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonCodeGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "group_code",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
            ],
            options={
                "db_table": "common_code_group",
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="ix_common_code_group_active",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            group_code__regex=(
                                "^[A-Z][A-Z0-9_]*$"
                            )
                        ),
                        name="ck_common_code_group_code_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            display_order__gte=0
                        ),
                        name=(
                            "ck_common_code_group_order_"
                            "nonnegative"
                        ),
                    ),
                ],
            },
        ),
    ]
