# Generated by Django 5.2.16 on 2026-07-30

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common_codes.db_expressions
import apps.common_codes.validators


class Migration(migrations.Migration):

    dependencies = [
        ("common_codes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonCode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=40),
                ),
                (
                    "code_name",
                    models.CharField(max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[
                            apps.common_codes.validators.validate_json_object
                        ],
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_code",
                        on_delete=(
                            django.db.models.deletion.PROTECT
                        ),
                        related_name="codes",
                        to="common_codes.commoncodegroup",
                    ),
                ),
            ],
            options={
                "db_table": "common_code",
                "indexes": [
                    models.Index(
                        fields=[
                            "group",
                            "is_active",
                            "display_order",
                        ],
                        name="ix_common_code_active",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "code"),
                        name="ux_common_code_group_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            code__regex="^[A-Z][A-Z0-9_]*$"
                        ),
                        name="ck_common_code_code_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            display_order__gte=0
                        ),
                        name="ck_common_code_order_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=(
                            apps.common_codes.db_expressions.IsJSONObject(
                                models.F("metadata")
                            )
                        ),
                        name="ck_common_code_metadata_object",
                    ),
                ],
            },
        ),
    ]
