# Generated by Django 5.2.16 on 2026-07-30 12:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def add_source_document_scope_foreign_keys(apps, schema_editor):
    """Add PostgreSQL-only composite FKs that preserve dataset scope."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE knowledge_source_document
        ADD CONSTRAINT fk_source_document_batch_scope
        FOREIGN KEY (ingestion_batch_id, dataset_scope_code)
        REFERENCES knowledge_ingestion_batch (id, dataset_scope_code)
        ON DELETE RESTRICT
        """
    )
    schema_editor.execute(
        """
        ALTER TABLE knowledge_source_document
        ADD CONSTRAINT fk_source_document_supersedes_scope
        FOREIGN KEY (supersedes_document_id, dataset_scope_code)
        REFERENCES knowledge_source_document (id, dataset_scope_code)
        MATCH SIMPLE
        ON DELETE RESTRICT
        """
    )


def remove_source_document_scope_foreign_keys(apps, schema_editor):
    """Remove PostgreSQL-only composite FKs in dependency-safe order."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE knowledge_source_document
        DROP CONSTRAINT IF EXISTS fk_source_document_supersedes_scope
        """
    )
    schema_editor.execute(
        """
        ALTER TABLE knowledge_source_document
        DROP CONSTRAINT IF EXISTS fk_source_document_batch_scope
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_promote_integer_primary_keys"),
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "document_code",
                    models.CharField(max_length=80),
                ),
                (
                    "dataset_scope_code",
                    models.CharField(
                        choices=[
                            ("MVP", "MVP"),
                            ("EXPANSION", "Expansion"),
                        ],
                        default="MVP",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300),
                ),
                (
                    "source_org",
                    models.CharField(max_length=150),
                ),
                (
                    "document_type_code",
                    models.CharField(max_length=40),
                ),
                (
                    "official_source_url",
                    models.CharField(max_length=1000),
                ),
                (
                    "usage_terms_url",
                    models.CharField(max_length=1000),
                ),
                (
                    "license_note",
                    models.TextField(),
                ),
                (
                    "original_file_uri",
                    models.CharField(max_length=1000),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(max_length=64),
                ),
                (
                    "revision_label",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "published_on",
                    models.DateField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        default="COLLECTED",
                        max_length=40,
                    ),
                ),
                (
                    "parser_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        db_column="collected_by_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collected_source_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="deleted_by_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleted_source_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingestion_batch",
                    models.ForeignKey(
                        db_column="ingestion_batch_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_documents",
                        to="evidence.ingestionbatch",
                    ),
                ),
                (
                    "supersedes_document",
                    models.ForeignKey(
                        blank=True,
                        db_column="supersedes_document_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseding_documents",
                        to="evidence.sourcedocument",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_source_document",
                "indexes": [
                    models.Index(
                        fields=[
                            "document_type_code",
                            "status_code",
                            "-collected_at",
                        ],
                        name="ix_source_document_status",
                    ),
                    models.Index(
                        fields=[
                            "official_source_url",
                            "revision_label",
                        ],
                        name="ix_source_document_revision",
                    ),
                    models.Index(
                        fields=["supersedes_document"],
                        name="ix_source_document_supersedes",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("deleted_at__isnull", True)
                        ),
                        fields=["status_code", "-collected_at"],
                        name="ix_source_doc_active_status",
                    ),
                    models.Index(
                        fields=["ingestion_batch"],
                        name="ix_source_document_batch",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_code",),
                        name="ux_source_document_code",
                    ),
                    models.UniqueConstraint(
                        fields=("sha256_hash",),
                        name="ux_source_document_sha256",
                    ),
                    models.UniqueConstraint(
                        fields=("id", "dataset_scope_code"),
                        name="ux_source_document_id_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("file_size_bytes__isnull", True),
                            ("file_size_bytes__gte", 0),
                            _connector="OR",
                        ),
                        name="ck_source_document_file_size",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "sha256_hash__regex",
                                "^[0-9a-f]{64}$",
                            )
                        ),
                        name="ck_source_document_sha256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "supersedes_document__isnull",
                                True,
                            ),
                            models.Q(
                                (
                                    "supersedes_document",
                                    models.F("id"),
                                ),
                                _negated=True,
                            ),
                            _connector="OR",
                        ),
                        name="ck_source_document_not_self_supersede",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("deleted_at__isnull", True),
                                ("deleted_by__isnull", True),
                            ),
                            models.Q(
                                ("deleted_at__isnull", False),
                                ("deleted_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_source_document_deleted_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "dataset_scope_code__in",
                                ["MVP", "EXPANSION"],
                            )
                        ),
                        name=(
                            "ck_knowledge_source_document_"
                            "dataset_scope_code_allowed"
                        ),
                    ),
                ],
            },
        ),
        migrations.RunPython(
            add_source_document_scope_foreign_keys,
            remove_source_document_scope_foreign_keys,
        ),
    ]
