# Generated by Django 5.2.16 on 2026-07-30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_promote_integer_primary_keys"),
        ("evidence", "0002_sourcedocument"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModelScope",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "applicable_from",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "applicable_to",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "applicability_note",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False),
                ),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_model_scopes",
                        to="evidence.sourcedocument",
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        db_column="product_model_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_scopes",
                        to="products.productmodel",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="verified_by_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_document_model_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_document_model_scope",
                "indexes": [
                    models.Index(
                        fields=[
                            "product_model",
                            "is_verified",
                            "applicable_from",
                            "applicable_to",
                        ],
                        name="ix_model_scope_model",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "product_model"),
                        name="ux_document_model_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("applicable_to__isnull", True),
                            ("applicable_from__isnull", True),
                            (
                                "applicable_to__gte",
                                models.F("applicable_from"),
                            ),
                            _connector="OR",
                        ),
                        name="ck_model_scope_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_verified", True),
                                ("verified_at__isnull", False),
                                ("verified_by__isnull", False),
                            ),
                            models.Q(
                                ("is_verified", False),
                                ("verified_at__isnull", True),
                                ("verified_by__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_model_scope_verification",
                    ),
                ],
            },
        ),
    ]
