# Generated by Django 5.2.16 on 2026-07-30.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_promote_integer_primary_keys"),
        ("evidence", "0003_documentmodelscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("page_no", models.IntegerField()),
                (
                    "extracted_text",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "text_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "parse_status_code",
                    models.CharField(
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                (
                    "review_status_code",
                    models.CharField(
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                (
                    "is_rag_eligible",
                    models.BooleanField(default=False),
                ),
                (
                    "exclusion_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_column="document_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="evidence.sourcedocument",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_column="reviewer_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_document_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_document_page",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("is_rag_eligible", True)
                        ),
                        fields=["document", "page_no"],
                        name="ix_document_page_rag",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "page_no"),
                        name="ux_document_page_no",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("page_no__gt", 0)),
                        name="ck_document_page_no",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("text_sha256__isnull", True),
                            (
                                "text_sha256__regex",
                                "^[0-9a-f]{64}$",
                            ),
                            _connector="OR",
                        ),
                        name="ck_document_page_sha256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reviewed_at__isnull", True),
                                ("reviewer__isnull", True),
                            ),
                            models.Q(
                                ("reviewed_at__isnull", False),
                                ("reviewer__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_document_page_review_bundle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_rag_eligible", False),
                            models.Q(
                                ("exclusion_reason__isnull", True),
                                ("extracted_text__isnull", False),
                                ("parse_status_code", "PARSED"),
                                ("review_status_code", "APPROVED"),
                                ("reviewed_at__isnull", False),
                                ("reviewer__isnull", False),
                                ("text_sha256__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_document_page_rag_eligibility",
                    ),
                ],
            },
        ),
    ]
