# Generated by Django 5.2.16 on 2026-07-30

import apps.evidence.models.document_chunk
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_document_chunk_fts_index(apps, schema_editor):
    """Create the PostgreSQL-only GIN index for the generated tsvector."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        CREATE INDEX ix_document_chunk_fts
        ON knowledge_document_chunk
        USING GIN (search_vector)
        """
    )


def drop_document_chunk_fts_index(apps, schema_editor):
    """Drop the PostgreSQL-only GIN index before table rollback."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        DROP INDEX IF EXISTS ix_document_chunk_fts
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0004_documentpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("chunk_no", models.IntegerField()),
                (
                    "chunk_type_code",
                    models.CharField(
                        default="PARAGRAPH",
                        max_length=40,
                    ),
                ),
                (
                    "section_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                    ),
                ),
                ("chunk_text", models.TextField()),
                (
                    "chunk_text_sha256",
                    models.CharField(max_length=64),
                ),
                (
                    "start_offset",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "end_offset",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "token_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tokenizer_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "tokenizer_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "symptom_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=(
                            apps.evidence.models.document_chunk
                            .SimpleSearchVector(
                                models.F("chunk_text")
                            )
                        ),
                        output_field=(
                            django.contrib.postgres.search
                            .SearchVectorField()
                        ),
                    ),
                ),
                (
                    "chunking_version",
                    models.CharField(max_length=50),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        db_column="page_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chunks",
                        to="evidence.documentpage",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_document_chunk",
                "indexes": [
                    models.Index(
                        fields=["page", "is_active"],
                        name="ix_document_chunk_active",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "page",
                            "chunk_no",
                            "chunking_version",
                        ),
                        name="ux_document_chunk_version",
                    ),
                    models.UniqueConstraint(
                        fields=("id", "chunk_text_sha256"),
                        name="ux_document_chunk_id_hash",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("page", "chunk_no"),
                        name="ux_document_chunk_active_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("chunk_no__gt", 0)),
                        name="ck_document_chunk_no",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("chunk_text__regex", "\\S")
                        ),
                        name="ck_document_chunk_text",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "chunk_text_sha256__regex",
                                "^[0-9a-f]{64}$",
                            )
                        ),
                        name="ck_document_chunk_hash",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_offset__isnull", True),
                                ("start_offset__isnull", True),
                            ),
                            models.Q(
                                (
                                    "end_offset__gt",
                                    models.F("start_offset"),
                                ),
                                ("end_offset__isnull", False),
                                ("start_offset__gte", 0),
                                ("start_offset__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_document_chunk_offsets",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("token_count__isnull", True),
                            ("token_count__gte", 0),
                            _connector="OR",
                        ),
                        name="ck_document_chunk_token_count",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                apps.evidence.models.document_chunk
                                .IsJSONArray(
                                    models.F("symptom_tags")
                                )
                            ),
                            (
                                apps.evidence.models.document_chunk
                                .IsJSONObject(models.F("metadata"))
                            ),
                        ),
                        name="ck_document_chunk_json",
                    ),
                ],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_document_chunk_fts_index,
                    drop_document_chunk_fts_index,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="documentchunk",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="ix_document_chunk_fts",
                    ),
                ),
            ],
        ),
    ]
