# Generated by Django 5.2.16 on 2026-07-30

import apps.evidence.models.document_chunk
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_promote_integer_primary_keys"),
        ("evidence", "0005_documentchunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "issue_type_code",
                    models.CharField(max_length=40),
                ),
                (
                    "validation_rule_code",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "validator_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "severity_code",
                    models.CharField(
                        default="ERROR",
                        max_length=40,
                    ),
                ),
                ("issue_message", models.TextField()),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        default="OPEN",
                        max_length=40,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        db_column="chunk_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_quality_issues",
                        to="evidence.documentchunk",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        db_column="document_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_quality_issues",
                        to="evidence.sourcedocument",
                    ),
                ),
                (
                    "ingestion_batch",
                    models.ForeignKey(
                        blank=True,
                        db_column="ingestion_batch_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_quality_issues",
                        to="evidence.ingestionbatch",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        db_column="page_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_quality_issues",
                        to="evidence.documentpage",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="resolved_by_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_data_quality_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_data_quality_issue",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            (
                                "status_code__in",
                                ["OPEN", "IN_REVIEW"],
                            )
                        ),
                        fields=["severity_code", "detected_at"],
                        name="ix_quality_issue_open",
                    ),
                    models.Index(
                        fields=["document", "page"],
                        name="ix_quality_issue_document",
                    ),
                    models.Index(
                        fields=["page"],
                        name="ix_quality_issue_page",
                    ),
                    models.Index(
                        fields=["chunk"],
                        name="ix_quality_issue_chunk",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("chunk__isnull", True),
                                ("document__isnull", False),
                                ("page__isnull", True),
                            ),
                            models.Q(
                                ("chunk__isnull", True),
                                ("document__isnull", True),
                                ("page__isnull", False),
                            ),
                            models.Q(
                                ("chunk__isnull", False),
                                ("document__isnull", True),
                                ("page__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_quality_issue_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("resolution_note__isnull", True),
                                ("resolved_at__isnull", True),
                                ("resolved_by__isnull", True),
                            ),
                            models.Q(
                                ("resolution_note__isnull", False),
                                ("resolved_at__isnull", False),
                                ("resolved_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ck_quality_issue_resolution_bundle",
                    ),
                    models.CheckConstraint(
                        condition=(
                            apps.evidence.models.document_chunk
                            .IsJSONObject(models.F("details"))
                        ),
                        name="ck_quality_issue_details_object",
                    ),
                ],
            },
        ),
    ]
