# Generated by Django 5.2.16 on 2026-07-30

import apps.evidence.models.chunk_embedding
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension, VectorField


class PortableVectorExtension(VectorExtension):
    """Keep the official vector operation reversible on SQLite tests."""

    def database_backwards(
        self,
        app_label,
        schema_editor,
        from_state,
        to_state,
    ):
        if schema_editor.connection.vendor != "postgresql":
            return
        super().database_backwards(
            app_label,
            schema_editor,
            from_state,
            to_state,
        )


def create_chunk_embedding_source_hash_fk(apps, schema_editor):
    """Bind an embedding to the exact source text version on PostgreSQL."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE knowledge_chunk_embedding
        ADD CONSTRAINT fk_chunk_embedding_source_hash
        FOREIGN KEY (chunk_id, source_text_sha256)
        REFERENCES knowledge_document_chunk (id, chunk_text_sha256)
        ON DELETE RESTRICT
        """
    )


def drop_chunk_embedding_source_hash_fk(apps, schema_editor):
    """Remove the PostgreSQL composite source-version foreign key."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE knowledge_chunk_embedding
        DROP CONSTRAINT IF EXISTS fk_chunk_embedding_source_hash
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0006_dataqualityissue"),
    ]

    operations = [
        PortableVectorExtension(),
        migrations.CreateModel(
            name="ChunkEmbedding",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(max_length=120),
                ),
                (
                    "embedding_model_version",
                    models.CharField(max_length=80),
                ),
                (
                    "embedding_dimension",
                    models.PositiveIntegerField(),
                ),
                (
                    "source_text_sha256",
                    models.CharField(max_length=64),
                ),
                (
                    "embedding",
                    VectorField(dimensions=1024),
                ),
                (
                    "embedded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        db_column="chunk_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="embeddings",
                        to="evidence.documentchunk",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_chunk_embedding",
                "indexes": [
                    models.Index(
                        fields=["embedding_model", "is_active"],
                        name="ix_chunk_embedding_active",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "chunk",
                            "embedding_model",
                            "embedding_model_version",
                        ),
                        name="ux_chunk_embedding_model",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("embedding_dimension", 1024),
                            (
                                "embedding_dimension",
                                apps.evidence.models.chunk_embedding
                                .VectorDimensions(
                                    models.F("embedding")
                                ),
                            ),
                        ),
                        name="ck_chunk_embedding_dimension",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source_text_sha256__regex",
                                "^[0-9a-f]{64}$",
                            )
                        ),
                        name="ck_chunk_embedding_source_hash",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("embedding_model__regex", "\\S")
                        ),
                        name="ck_chunk_embedding_model_name",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "embedding_model_version__regex",
                                "\\S",
                            )
                        ),
                        name="ck_chunk_embedding_model_version",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_chunk_embedding_source_hash_fk,
            drop_chunk_embedding_source_hash_fk,
        ),
    ]
