# Generated by Django 5.2.16 on 2026-08-12 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0008_evidencelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChunkCrosswalk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('canonical_chunk_id', models.CharField(max_length=160, unique=True)),
                ('manifest_schema_version', models.CharField(max_length=40)),
                ('identity_manifest_sha256', models.CharField(max_length=64)),
                ('canonical_verification_status', models.CharField(max_length=60)),
                ('source_file_sha256', models.CharField(max_length=64)),
                ('chunk_text_sha256', models.CharField(max_length=64)),
                ('embedding_model', models.CharField(max_length=120)),
                ('embedding_model_version', models.CharField(max_length=80)),
                ('index_version', models.CharField(max_length=40)),
                ('chunk_set_sha256', models.CharField(max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('chunk', models.OneToOneField(db_column='chunk_id', on_delete=django.db.models.deletion.PROTECT, related_name='ai_crosswalk', to='evidence.documentchunk')),
                ('model_scope', models.ForeignKey(db_column='model_scope_id', on_delete=django.db.models.deletion.PROTECT, related_name='ai_chunk_crosswalks', to='evidence.documentmodelscope')),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_ai_chunk_crosswalks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_ai_chunk_crosswalk',
            },
        ),
        migrations.CreateModel(
            name='AIChunkCrosswalkPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField()),
                ('crosswalk', models.ForeignKey(db_column='crosswalk_id', on_delete=django.db.models.deletion.CASCADE, related_name='source_pages', to='evidence.aichunkcrosswalk')),
                ('page', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.PROTECT, related_name='ai_chunk_crosswalk_pages', to='evidence.documentpage')),
            ],
            options={
                'db_table': 'knowledge_ai_chunk_crosswalk_page',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aichunkcrosswalk',
            index=models.Index(fields=['is_active', 'is_verified'], name='ix_ai_crosswalk_active'),
        ),
        migrations.AddIndex(
            model_name='aichunkcrosswalk',
            index=models.Index(fields=['embedding_model', 'embedding_model_version'], name='ix_ai_crosswalk_embedding'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(('canonical_chunk_id__regex', '^RAG-[A-Z0-9]+(?:-[A-Z0-9]+)*$')), name='ck_ai_crosswalk_canonical_id'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(('identity_manifest_sha256__regex', '^[0-9a-f]{64}$')), name='ck_ai_crosswalk_manifest_hash'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(('source_file_sha256__regex', '^[0-9a-f]{64}$')), name='ck_ai_crosswalk_source_hash'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(('chunk_text_sha256__regex', '^[0-9a-f]{64}$')), name='ck_ai_crosswalk_chunk_hash'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(('chunk_set_sha256__regex', '^[0-9a-f]{64}$')), name='ck_ai_crosswalk_set_hash'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_verified', True), ('verified_at__isnull', False), ('verified_by__isnull', False)), models.Q(('is_verified', False), ('verified_at__isnull', True), ('verified_by__isnull', True)), _connector='OR'), name='ck_ai_crosswalk_verified_bundle'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('is_verified', True), _connector='OR'), name='ck_ai_crosswalk_active_verified'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalkpage',
            constraint=models.UniqueConstraint(fields=('crosswalk', 'page'), name='ux_ai_crosswalk_page'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalkpage',
            constraint=models.UniqueConstraint(fields=('crosswalk', 'display_order'), name='ux_ai_crosswalk_page_order'),
        ),
        migrations.AddConstraint(
            model_name='aichunkcrosswalkpage',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gt', 0)), name='ck_ai_crosswalk_page_order'),
        ),
    ]
