# Generated by Django 5.2.16 on 2026-07-28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_add_public_identifiers"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSubscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "contract_no",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "serial_no",
                    models.CharField(max_length=80),
                ),
                (
                    "management_type_code",
                    models.CharField(
                        choices=[
                            ("SELF_MANAGED", "자가관리"),
                            ("VISIT_CARE", "방문관리"),
                        ],
                        default="VISIT_CARE",
                        max_length=40,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "이용 중"),
                            ("SUSPENDED", "일시 중지"),
                            ("CANCELLED", "해지"),
                            ("EXPIRED", "만료"),
                        ],
                        default="ACTIVE",
                        max_length=40,
                    ),
                ),
                ("started_on", models.DateField()),
                (
                    "ended_on",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "installed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "installation_address",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "next_care_on",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        db_column="product_model_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="products.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_customer_subscription",
                "indexes": [
                    models.Index(
                        fields=["customer", "status_code"],
                        name="ix_sub_customer_status",
                    ),
                    models.Index(
                        condition=(
                            models.Q(status_code="ACTIVE")
                            & models.Q(next_care_on__isnull=False)
                        ),
                        fields=["next_care_on"],
                        name="ix_sub_next_care",
                    ),
                    models.Index(
                        fields=["product_model"],
                        name="ix_sub_product_model",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            status_code__in=[
                                "ACTIVE",
                                "SUSPENDED",
                            ]
                        ),
                        fields=("serial_no",),
                        name="ux_sub_active_serial",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(ended_on__isnull=True)
                            | models.Q(
                                ended_on__gte=models.F("started_on")
                            )
                        ),
                        name="ck_subscription_period",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(
                                status_code__in=[
                                    "CANCELLED",
                                    "EXPIRED",
                                ]
                            )
                            | models.Q(ended_on__isnull=False)
                        ),
                        name="ck_subscription_ended_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            management_type_code__in=[
                                "SELF_MANAGED",
                                "VISIT_CARE",
                            ]
                        ),
                        name="ck_sub_management_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            status_code__in=[
                                "ACTIVE",
                                "SUSPENDED",
                                "CANCELLED",
                                "EXPIRED",
                            ]
                        ),
                        name="ck_sub_status_code",
                    ),
                ],
            },
        ),
    ]
