# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersubscription",
            name="installed_on",
            field=models.DateField(
                blank=True,
                help_text="원본이 날짜 정밀도만 제공할 때 사용하는 설치일",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customersubscription",
            name="source_customer_product_public_id",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text=(
                    "CustomerProduct fixture를 별도 테이블 없이 투영한 원본 UUID"
                ),
                null=True,
                unique=True,
            ),
        ),
    ]
