# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquiries", "0003_add_synthetic_handoff_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "consultation_code",
                    models.CharField(max_length=50, unique=True),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="WAITING",
                        max_length=40,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            (
                                "COMPLETED_NO_VISIT",
                                "Completed without visit",
                            ),
                            ("VISIT_REQUIRED", "Visit required"),
                            (
                                "REOPENED_FOLLOWUP",
                                "Reopened follow-up",
                            ),
                        ],
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "state_version",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=128),
                ),
                ("correlation_id", models.UUIDField()),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic"),
                            ("operational", "Operational"),
                        ],
                        default="operational",
                        max_length=40,
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        db_column="consultant_id",
                        db_index=False,
                        limit_choices_to={"role_code": "CONSULTANT"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        db_column="inquiry_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
            options={
                "db_table": "support_consultation",
                "indexes": [
                    models.Index(
                        fields=["inquiry", "-created_at"],
                        name="ix_consult_inquiry_created",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ix_consult_queue",
                    ),
                    models.Index(
                        fields=["consultant", "status"],
                        name="ix_consult_staff_status",
                    ),
                    models.Index(
                        fields=["correlation_id"],
                        name="ix_consult_correlation",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inquiry", "sequence"),
                        name="ux_consult_inquiry_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gt", 0)),
                        name="ck_consult_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state_version__gt", 0)),
                        name="ck_consult_state_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "WAITING",
                                    "ASSIGNED",
                                    "IN_PROGRESS",
                                    "COMPLETED",
                                    "CANCELLED",
                                ],
                            )
                        ),
                        name="ck_consult_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "outcome__in",
                                [
                                    "PENDING",
                                    "COMPLETED_NO_VISIT",
                                    "VISIT_REQUIRED",
                                    "REOPENED_FOLLOWUP",
                                ],
                            )
                        ),
                        name="ck_consult_outcome",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "data_classification__in",
                                ["synthetic", "operational"],
                            )
                        ),
                        name="ck_consult_data_class",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("summary", ""),
                            _negated=True,
                        ),
                        name="ck_consult_summary_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("idempotency_key", ""),
                            _negated=True,
                        ),
                        name="ck_consult_idempotency_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("consultant__isnull", True),
                                ("started_at__isnull", True),
                                ("status", "WAITING"),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("consultant__isnull", False),
                                ("started_at__isnull", True),
                                ("status", "ASSIGNED"),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("consultant__isnull", False),
                                ("started_at__isnull", False),
                                ("status", "IN_PROGRESS"),
                            )
                            | models.Q(
                                ("completed_at__isnull", False),
                                ("consultant__isnull", False),
                                ("started_at__isnull", False),
                                ("status", "COMPLETED"),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("status", "CANCELLED"),
                            )
                        ),
                        name="ck_consult_lifecycle",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                (
                                    "outcome__in",
                                    [
                                        "COMPLETED_NO_VISIT",
                                        "VISIT_REQUIRED",
                                        "REOPENED_FOLLOWUP",
                                    ],
                                ),
                                ("status", "COMPLETED"),
                            )
                            | (
                                models.Q(
                                    ("status", "COMPLETED"),
                                    _negated=True,
                                )
                                & models.Q(("outcome", "PENDING"))
                            )
                        ),
                        name="ck_consult_outcome_lifecycle",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("started_at__isnull", True))
                            | models.Q(
                                (
                                    "started_at__gte",
                                    models.F("created_at"),
                                )
                            )
                        ),
                        name="ck_consult_start_order",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("completed_at__isnull", True))
                            | models.Q(
                                (
                                    "completed_at__gte",
                                    models.F("started_at"),
                                )
                            )
                        ),
                        name="ck_consult_complete_order",
                    ),
                ],
            },
        ),
    ]
