# Generated by Django 5.2.16 on 2026-07-28 04:38

import apps.inquiries.models.inquiry
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "inquiry_code",
                    models.CharField(
                        default=(
                            apps.inquiries.models.inquiry
                            .generate_inquiry_code
                        ),
                        editable=False,
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "channel_code",
                    models.CharField(
                        choices=[
                            ("WEB", "Web"),
                            ("MOBILE", "Mobile"),
                            ("PHONE", "Phone"),
                            ("OPERATOR", "Operator"),
                        ],
                        max_length=40,
                    ),
                ),
                ("raw_text", models.TextField()),
                (
                    "questionnaire_session_public_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            (
                                "QUESTIONNAIRE_IN_PROGRESS",
                                "Questionnaire in progress",
                            ),
                            ("AI_GUIDANCE", "AI guidance"),
                            (
                                "CONSULTATION_REQUIRED",
                                "Consultation required",
                            ),
                            (
                                "CONSULTATION_IN_PROGRESS",
                                "Consultation in progress",
                            ),
                            (
                                "VISIT_REVIEW_PENDING",
                                "Visit review pending",
                            ),
                            (
                                "VISIT_SCHEDULING",
                                "Visit scheduling",
                            ),
                            (
                                "VISIT_SCHEDULED",
                                "Visit scheduled",
                            ),
                            (
                                "COMPLETION_PENDING",
                                "Completion pending",
                            ),
                            (
                                "REVISIT_REQUIRED",
                                "Revisit required",
                            ),
                            ("REOPENED", "Reopened"),
                            ("RESOLVED", "Resolved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                (
                    "state_version",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cancellation_reason_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "cancellation_reason_detail",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        db_column="initiated_by_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        db_column="subscription_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiries",
                        to="subscriptions.customersubscription",
                    ),
                ),
            ],
            options={
                "db_table": "support_inquiry",
            },
        ),
        migrations.CreateModel(
            name="SymptomEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "symptom_type_code",
                    models.CharField(max_length=40),
                ),
                (
                    "structured_payload",
                    models.JSONField(default=dict),
                ),
                (
                    "schema_version",
                    models.CharField(default="v1", max_length=30),
                ),
                (
                    "is_customer_confirmed",
                    models.BooleanField(default=True),
                ),
                (
                    "inquiry",
                    models.OneToOneField(
                        db_column="inquiry_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representative_symptom",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
            options={
                "db_table": "support_inquiry_symptom",
            },
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["subscription", "status_code"],
                name="ix_inquiry_subscription_status",
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["initiated_by", "status_code"],
                name="ix_inquiry_actor_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "channel_code__in",
                        ["WEB", "MOBILE", "PHONE", "OPERATOR"],
                    )
                ),
                name="ck_inquiry_channel_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status_code__in",
                        [
                            "DRAFT",
                            "QUESTIONNAIRE_IN_PROGRESS",
                            "AI_GUIDANCE",
                            "CONSULTATION_REQUIRED",
                            "CONSULTATION_IN_PROGRESS",
                            "VISIT_REVIEW_PENDING",
                            "VISIT_SCHEDULING",
                            "VISIT_SCHEDULED",
                            "COMPLETION_PENDING",
                            "REVISIT_REQUIRED",
                            "REOPENED",
                            "RESOLVED",
                            "CANCELLED",
                        ],
                    )
                ),
                name="ck_inquiry_status_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(("state_version__gt", 0)),
                name="ck_inquiry_state_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(("raw_text", ""), _negated=True),
                name="ck_inquiry_raw_text_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="symptomentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("symptom_type_code", ""),
                    _negated=True,
                ),
                name="ck_inquiry_symptom_code_nonempty",
            ),
        ),
    ]
