# Generated by Django 5.2.16 on 2026-07-28 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="cancellation_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER_REQUEST", "Customer request"),
                    ("DUPLICATE_INQUIRY", "Duplicate inquiry"),
                    ("ISSUE_RESOLVED", "Issue resolved"),
                    ("OTHER", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancellation_reason_code__isnull", True),
                    (
                        "cancellation_reason_code__in",
                        [
                            "CUSTOMER_REQUEST",
                            "DUPLICATE_INQUIRY",
                            "ISSUE_RESOLVED",
                            "OTHER",
                        ],
                    ),
                    _connector="OR",
                ),
                name="ck_inquiry_cancel_reason_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cancellation_reason_code__isnull", False),
                        ("cancelled_at__isnull", False),
                        ("status_code", "CANCELLED"),
                    ),
                    models.Q(
                        models.Q(
                            ("status_code", "CANCELLED"),
                            _negated=True,
                        ),
                        ("cancelled_at__isnull", True),
                        ("cancellation_reason_code__isnull", True),
                        ("cancellation_reason_detail__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_inquiry_cancellation_fields",
            ),
        ),
    ]
