# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0002_alter_inquiry_cancellation_reason_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="assigned_role_code",
            field=models.CharField(
                choices=[
                    ("NONE", "No assignee"),
                    ("CONSULTANT", "Consultant"),
                    ("TECHNICIAN", "Technician"),
                ],
                default="NONE",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                db_column="assigned_user_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="evidence_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="evidence_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXACT_MODEL", "Exact model evidence"),
                    ("NO_EVIDENCE", "No evidence"),
                    ("PARTIAL_EVIDENCE", "Partial evidence"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="requires_fallback",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="risk_level_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("caution", "Caution"),
                    ("danger", "Danger"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="scenario_code",
            field=models.CharField(
                blank=True,
                help_text="합성 시나리오 추적용 업무 식별자",
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="source_correlation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="source_idempotency_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="usage_guidance_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NORMAL", "Normal use"),
                    ("PARTIAL_STOP", "Partial stop"),
                    ("TOTAL_STOP", "Total stop"),
                    (
                        "PENDING_CONSULTATION",
                        "Pending consultation",
                    ),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="channel_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEB", "Web"),
                    ("MOBILE", "Mobile"),
                    ("PHONE", "Phone"),
                    ("OPERATOR", "Operator"),
                ],
                help_text="원본에 접수 채널이 없으면 NULL로 보존",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    assigned_role_code__in=[
                        "NONE",
                        "CONSULTANT",
                        "TECHNICIAN",
                    ]
                ),
                name="ck_inquiry_assigned_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        assigned_role_code="NONE",
                        assigned_user__isnull=True,
                    )
                    | models.Q(
                        assigned_role_code__in=[
                            "CONSULTANT",
                            "TECHNICIAN",
                        ],
                        assigned_user__isnull=False,
                    )
                ),
                name="ck_inquiry_assignment_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(risk_level_code__isnull=True)
                    | models.Q(
                        risk_level_code__in=[
                            "general",
                            "caution",
                            "danger",
                        ]
                    )
                ),
                name="ck_inquiry_risk_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(usage_guidance_status__isnull=True)
                    | models.Q(
                        usage_guidance_status__in=[
                            "NORMAL",
                            "PARTIAL_STOP",
                            "TOTAL_STOP",
                            "PENDING_CONSULTATION",
                        ]
                    )
                ),
                name="ck_inquiry_usage_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="inquiry",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(evidence_mode__isnull=True)
                    | models.Q(
                        evidence_mode__in=[
                            "EXACT_MODEL",
                            "NO_EVIDENCE",
                            "PARTIAL_EVIDENCE",
                        ]
                    )
                ),
                name="ck_inquiry_evidence_mode",
            ),
        ),
    ]
