# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
        ("inquiries", "0003_add_synthetic_handoff_fields"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowupConfirmation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "followup_code",
                    models.CharField(max_length=60, unique=True),
                ),
                (
                    "guidance_public_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "channel_code",
                    models.CharField(
                        choices=[
                            ("APP", "App"),
                            ("WEB", "Web"),
                            ("PHONE", "Phone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resolution_status_code",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RESOLVED", "Resolved"),
                            ("UNRESOLVED", "Unresolved"),
                            ("REOPENED", "Reopened"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "state_version",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "customer_response",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "unresolved_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "next_action",
                    models.CharField(
                        choices=[
                            ("FINALIZE_INQUIRY", "Finalize inquiry"),
                            ("RESUME_CONSULTATION", "Resume consultation"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=40,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        db_column="consultation_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="followup_confirmations",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        db_column="inquiry_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="followup_confirmations",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        db_column="visit_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="followup_confirmations",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "db_table": "support_followup_confirmation",
                "indexes": [
                    models.Index(
                        fields=["inquiry", "-requested_at"],
                        name="ix_followup_inquiry",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(state_version__gt=0),
                        name="ck_followup_state_version",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                resolution_status_code="PENDING",
                                responded_at__isnull=True,
                                confirmed_at__isnull=True,
                            )
                            | models.Q(
                                resolution_status_code__in=[
                                    "RESOLVED",
                                    "UNRESOLVED",
                                    "REOPENED",
                                ],
                                responded_at__isnull=False,
                            )
                        ),
                        name="ck_followup_response_state",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(
                                resolution_status_code__in=[
                                    "UNRESOLVED",
                                    "REOPENED",
                                ]
                            )
                            | models.Q(unresolved_reason__isnull=False)
                        ),
                        name="ck_followup_unresolved_reason",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(resolution_status_code="RESOLVED")
                            | models.Q(confirmed_at__isnull=False)
                        ),
                        name="ck_followup_resolved_confirmed",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(responded_at__isnull=True)
                            | models.Q(
                                responded_at__gte=models.F("requested_at")
                            )
                        ),
                        name="ck_followup_response_time",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(confirmed_at__isnull=True)
                            | (
                                models.Q(responded_at__isnull=False)
                                & models.Q(
                                    confirmed_at__gte=models.F("responded_at")
                                )
                            )
                        ),
                        name="ck_followup_confirmation_time",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(guidance_public_id__isnull=False)
                            | models.Q(consultation__isnull=False)
                            | models.Q(visit__isnull=False)
                        ),
                        name="ck_followup_has_source",
                    ),
                ],
            },
        ),
    ]
