# Generated by Django 5.2.16 on 2026-07-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0004_followup_confirmation"),
        ("subscriptions", "0002_add_synthetic_projection_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(fields=('id', 'subscription'), name='ux_inquiry_id_subscription'),
        ),
    ]
