# Generated by Django 5.2.16 on 2026-07-30 13:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0008_guidance"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidanceItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "step_no",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "action_type_code",
                    models.CharField(max_length=40),
                ),
                (
                    "instruction_text",
                    models.TextField(),
                ),
                (
                    "caution_text",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "requires_confirmation",
                    models.BooleanField(default=True),
                ),
                (
                    "guidance",
                    models.ForeignKey(
                        db_column="guidance_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inquiries.guidance",
                    ),
                ),
            ],
            options={
                "db_table": "support_guidance_item",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guidance", "step_no"),
                        name="ux_guidance_item_step",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("step_no__gt", 0)),
                        name="ck_guidance_item_step",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action_type_code__regex",
                                r".*\S.*",
                            )
                        ),
                        name="ck_guidance_action_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "instruction_text__regex",
                                r".*\S.*",
                            )
                        ),
                        name="ck_guidance_item_instruction",
                    ),
                ],
            },
        ),
    ]
