# Generated by Django 5.2.16 on 2026-07-30 13:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0009_guidanceitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerActionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "attempt_no",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "result_code",
                    models.CharField(max_length=40),
                ),
                (
                    "result_text",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "performed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "customer_comment",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=128),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "guidance_item",
                    models.ForeignKey(
                        db_column="guidance_item_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_results",
                        to="inquiries.guidanceitem",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        db_column="submitted_by_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name=(
                            "submitted_customer_action_results"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_customer_action_result",
                "indexes": [
                    models.Index(
                        fields=["guidance_item", "created_at"],
                        name="ix_action_result_guidance_item",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guidance_item", "attempt_no"),
                        name="ux_action_result_attempt",
                    ),
                    models.UniqueConstraint(
                        fields=("idempotency_key",),
                        name="ux_action_result_idempotency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_no__gt", 0)),
                        name="ck_action_result_attempt",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "result_code__regex",
                                r".*\S.*",
                            )
                        ),
                        name="ck_action_result_code_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "idempotency_key__regex",
                                r".*\S.*",
                            )
                        ),
                        name="ck_action_result_idem_nonempty",
                    ),
                ],
            },
        ),
    ]
