# Generated by Django 5.2.16 on 2026-09-01 08:22

import django.db.models.deletion
import uuid
import django.core.validators
from django.db import migrations, models


def require_empty_resume_dispatch_for_reverse(apps, schema_editor) -> None:
    """Block a table drop while durable dispatch evidence still exists."""

    ResumeDispatch = apps.get_model(
        "inquiries",
        "HumanReviewResumeDispatch",
    )
    using = schema_editor.connection.alias
    row_count = ResumeDispatch.objects.using(using).count()
    if row_count:
        raise RuntimeError(
            "inquiries.0018 reverse is blocked while HumanReview resume "
            f"dispatch rows exist: row_count={row_count}."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0017_consultationcauseledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReviewResumeDispatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('source_review_state_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHING', 'Dispatching'), ('SUCCEEDED', 'Succeeded'), ('FAILED_PRE_SEND', 'Failed before send'), ('OUTCOME_UNKNOWN', 'Outcome unknown')], default='PENDING', max_length=24)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('payload_sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='payload_sha256 must be lowercase SHA-256 hex', regex='^[0-9a-f]{64}$')])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('provider_calls', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('context_synthesis_status', models.CharField(blank=True, max_length=20, null=True)),
                ('fallback_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('handoff_delivery_scheduled', models.BooleanField(blank=True, null=True)),
                ('idempotent_replay', models.BooleanField(blank=True, null=True)),
                ('human_review', models.OneToOneField(db_column='human_review_id', on_delete=django.db.models.deletion.PROTECT, related_name='resume_dispatch', to='inquiries.humanreview')),
            ],
            options={
                'db_table': 'support_human_review_resume_dispatch',
                'indexes': [models.Index(fields=['status', 'created_at'], name='ix_hreview_resume_pending')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_review_state_version', 2)), name='ck_hreview_resume_source_version'), models.CheckConstraint(condition=models.Q(('attempt_count__lte', 1)), name='ck_hreview_resume_one_attempt'), models.CheckConstraint(condition=models.Q(models.Q(('attempt_count', 0), ('completed_at__isnull', True), ('context_synthesis_status__isnull', True), ('failure_code', ''), ('fallback_reason__isnull', True), ('handoff_delivery_scheduled__isnull', True), ('idempotent_replay__isnull', True), ('payload_sha256', ''), ('provider_calls__isnull', True), ('started_at__isnull', True), ('status', 'PENDING')), models.Q(('attempt_count', 1), ('completed_at__isnull', True), ('context_synthesis_status__isnull', True), ('failure_code', ''), ('fallback_reason__isnull', True), ('handoff_delivery_scheduled__isnull', True), ('idempotent_replay__isnull', True), ('payload_sha256__gt', ''), ('provider_calls__isnull', True), ('started_at__isnull', False), ('status', 'DISPATCHING')), models.Q(('attempt_count', 1), ('completed_at__isnull', False), ('context_synthesis_status__in', ['SUCCEEDED', 'FALLBACK', 'UNAVAILABLE']), ('failure_code', ''), ('handoff_delivery_scheduled__isnull', False), ('idempotent_replay__isnull', False), ('payload_sha256__gt', ''), ('provider_calls__in', [0, 1]), ('started_at__isnull', False), ('status', 'SUCCEEDED')), models.Q(('attempt_count', 0), ('completed_at__isnull', False), ('context_synthesis_status__isnull', True), ('failure_code__gt', ''), ('fallback_reason__isnull', True), ('handoff_delivery_scheduled__isnull', True), ('idempotent_replay__isnull', True), ('payload_sha256', ''), ('provider_calls__isnull', True), ('started_at__isnull', True), ('status', 'FAILED_PRE_SEND')), models.Q(('attempt_count', 1), ('completed_at__isnull', False), ('context_synthesis_status__isnull', True), ('failure_code__gt', ''), ('fallback_reason__isnull', True), ('handoff_delivery_scheduled__isnull', True), ('idempotent_replay__isnull', True), ('payload_sha256__gt', ''), ('provider_calls__isnull', True), ('started_at__isnull', False), ('status', 'OUTCOME_UNKNOWN')), _connector='OR'), name='ck_hreview_resume_dispatch_state'), models.CheckConstraint(condition=models.Q(('fallback_reason__isnull', True), ('context_synthesis_status', 'FALLBACK'), _connector='OR'), name='ck_hreview_resume_fallback_state'), models.CheckConstraint(condition=models.Q(models.Q(('context_synthesis_status', 'FALLBACK'), _negated=True), ('fallback_reason__isnull', False), _connector='OR'), name='ck_hreview_resume_fallback_reason'), models.CheckConstraint(condition=models.Q(models.Q(('context_synthesis_status', 'SUCCEEDED'), _negated=True), models.Q(('fallback_reason__isnull', True), ('provider_calls', 1)), _connector='OR'), name='ck_hreview_resume_provider_success')],
            },
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=require_empty_resume_dispatch_for_reverse,
        ),
    ]
