# Generated by Django 5.2.16 on 2026-07-28 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquiries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "operation_id",
                    models.CharField(max_length=80),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=128),
                ),
                (
                    "request_hash",
                    models.CharField(max_length=64),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "resource_public_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        db_column="actor_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_idempotency_record",
                "indexes": [
                    models.Index(
                        fields=["resource_public_id"],
                        name="ix_idempotency_resource",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "actor",
                            "operation_id",
                            "idempotency_key",
                        ),
                        name="ux_workflow_idempotency_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransitionHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "event_code",
                    models.CharField(max_length=80),
                ),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(max_length=40),
                ),
                (
                    "state_version",
                    models.PositiveIntegerField(),
                ),
                ("correlation_id", models.UUIDField()),
                (
                    "idempotency_key",
                    models.CharField(max_length=128),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        db_column="actor_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        db_column="inquiry_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transition_history",
                        to="inquiries.inquiry",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_transition_history",
                "indexes": [
                    models.Index(
                        fields=["correlation_id"],
                        name="ix_transition_correlation",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inquiry", "state_version"),
                        name="ux_transition_inquiry_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state_version__gt", 0)),
                        name="ck_transition_state_version_positive",
                    ),
                ],
            },
        ),
    ]
