# Generated by Django 5.2.16 on 2026-07-29

import apps.workflow.models.transition_history
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_status_history_codes(apps, schema_editor):
    del schema_editor
    model = apps.get_model("workflow", "TransitionHistory")
    for record in model.objects.filter(
        status_history_code__isnull=True
    ).iterator():
        record.status_history_code = (
            f"HST-{record.public_id.hex.upper()}"
        )
        record.save(update_fields=["status_history_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
        ("inquiries", "0003_add_synthetic_handoff_fields"),
        ("visits", "0001_initial"),
        ("workflow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transitionhistory",
            name="ux_transition_inquiry_version",
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="change_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="changed_at",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="changed_by_type_code",
            field=models.CharField(
                choices=[("USER", "User"), ("SYSTEM", "System")],
                default="USER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                db_column="consultation_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transition_history",
                to="consultations.consultation",
            ),
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="questionnaire_session_public_id",
            field=models.UUIDField(
                blank=True,
                help_text="Questionnaire 모델 도입 전 공개 UUID 호환 브리지",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="status_history_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="target_type_code",
            field=models.CharField(
                choices=[
                    ("QUESTIONNAIRE", "Questionnaire"),
                    ("INQUIRY", "Inquiry"),
                    ("CONSULTATION", "Consultation"),
                    ("VISIT", "Visit"),
                ],
                default="INQUIRY",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="transitionhistory",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                db_column="visit_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transition_history",
                to="visits.visit",
            ),
        ),
        migrations.AlterField(
            model_name="transitionhistory",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                db_column="actor_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transitionhistory",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                db_column="inquiry_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transition_history",
                to="inquiries.inquiry",
            ),
        ),
        migrations.RunPython(
            backfill_status_history_codes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="transitionhistory",
            name="status_history_code",
            field=models.CharField(
                default=(
                    apps.workflow.models.transition_history
                    .generate_status_history_code
                ),
                editable=False,
                max_length=60,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(target_type_code="INQUIRY"),
                fields=("inquiry", "state_version"),
                name="uq_hist_inquiry_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(target_type_code="CONSULTATION"),
                fields=("consultation", "state_version"),
                name="uq_hist_consult_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(target_type_code="VISIT"),
                fields=("visit", "state_version"),
                name="uq_hist_visit_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(target_type_code="QUESTIONNAIRE"),
                fields=(
                    "questionnaire_session_public_id",
                    "state_version",
                ),
                name="uq_hist_question_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        target_type_code="QUESTIONNAIRE",
                        questionnaire_session_public_id__isnull=False,
                        inquiry__isnull=True,
                        consultation__isnull=True,
                        visit__isnull=True,
                    )
                    | models.Q(
                        target_type_code="INQUIRY",
                        questionnaire_session_public_id__isnull=True,
                        inquiry__isnull=False,
                        consultation__isnull=True,
                        visit__isnull=True,
                    )
                    | models.Q(
                        target_type_code="CONSULTATION",
                        questionnaire_session_public_id__isnull=True,
                        inquiry__isnull=True,
                        consultation__isnull=False,
                        visit__isnull=True,
                    )
                    | models.Q(
                        target_type_code="VISIT",
                        questionnaire_session_public_id__isnull=True,
                        inquiry__isnull=True,
                        consultation__isnull=True,
                        visit__isnull=False,
                    )
                ),
                name="ck_hist_target_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        changed_by_type_code="USER",
                        actor__isnull=False,
                    )
                    | models.Q(
                        changed_by_type_code="SYSTEM",
                        actor__isnull=True,
                    )
                ),
                name="ck_hist_actor_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        state_version=1,
                        from_state__isnull=True,
                    )
                    | models.Q(
                        state_version__gt=1,
                        from_state__isnull=False,
                    )
                ),
                name="ck_hist_version_origin",
            ),
        ),
        migrations.AddIndex(
            model_name="transitionhistory",
            index=models.Index(
                condition=models.Q(target_type_code="INQUIRY"),
                fields=["inquiry", "event_code", "idempotency_key"],
                name="ix_hist_inquiry_event_idem",
            ),
        ),
        migrations.AddIndex(
            model_name="transitionhistory",
            index=models.Index(
                condition=models.Q(target_type_code="CONSULTATION"),
                fields=[
                    "consultation",
                    "event_code",
                    "idempotency_key",
                ],
                name="ix_hist_consult_event_idem",
            ),
        ),
        migrations.AddIndex(
            model_name="transitionhistory",
            index=models.Index(
                condition=models.Q(target_type_code="VISIT"),
                fields=["visit", "event_code", "idempotency_key"],
                name="ix_hist_visit_event_idem",
            ),
        ),
    ]
