# Generated by Django 5.2.16 on 2026-07-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_questionnaire_session_fk(apps, schema_editor):
    """Replace the transitional public-UUID bridge with the real FK."""

    using = schema_editor.connection.alias
    history_model = apps.get_model("workflow", "TransitionHistory")
    session_model = apps.get_model(
        "questionnaires",
        "QuestionnaireSession",
    )

    unexpected_bridge_rows = history_model.objects.using(using).exclude(
        target_type_code="QUESTIONNAIRE"
    ).filter(questionnaire_session_public_id__isnull=False)
    if unexpected_bridge_rows.exists():
        raise RuntimeError(
            "Non-questionnaire history rows contain questionnaire UUIDs."
        )

    if any(
        len(event_code) > 60
        for event_code in history_model.objects.using(using).values_list(
            "event_code",
            flat=True,
        )
    ):
        raise RuntimeError(
            "A status-history event_code exceeds the contract length 60."
        )

    rows = list(
        history_model.objects.using(using)
        .filter(target_type_code="QUESTIONNAIRE")
        .only(
            "id",
            "event_code",
            "questionnaire_session_public_id",
            "questionnaire_session_id",
        )
    )
    public_ids = {
        row.questionnaire_session_public_id
        for row in rows
        if row.questionnaire_session_public_id is not None
    }
    sessions = {
        public_id: internal_id
        for public_id, internal_id in session_model.objects.using(
            using
        )
        .filter(public_id__in=public_ids)
        .values_list("public_id", "id")
    }
    if len(public_ids) != len(sessions):
        missing = sorted(
            str(public_id)
            for public_id in public_ids - set(sessions)
        )
        raise RuntimeError(
            "Questionnaire history UUID bridge cannot be resolved: "
            + ", ".join(missing)
        )

    for row in rows:
        public_id = row.questionnaire_session_public_id
        if public_id is None:
            raise RuntimeError(
                "QUESTIONNAIRE history row has no questionnaire UUID."
            )
        row.questionnaire_session_id = sessions[public_id]
    if rows:
        history_model.objects.using(using).bulk_update(
            rows,
            ["questionnaire_session"],
            batch_size=500,
        )


def restore_questionnaire_session_bridge(apps, schema_editor):
    """Restore the public UUID bridge when rolling the contract FK back."""

    using = schema_editor.connection.alias
    history_model = apps.get_model("workflow", "TransitionHistory")
    rows = list(
        history_model.objects.using(using)
        .filter(questionnaire_session__isnull=False)
        .select_related("questionnaire_session")
    )
    for row in rows:
        row.questionnaire_session_public_id = (
            row.questionnaire_session.public_id
        )
    if rows:
        history_model.objects.using(using).bulk_update(
            rows,
            ["questionnaire_session_public_id"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('inquiries', '0006_symptomassessment'),
        ('questionnaires', '0002_postgresql_inquiry_subscription_fk'),
        ('visits', '0002_visitresult'),
        ('workflow', '0003_backfill_legacy_changed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionhistory',
            name='questionnaire_session',
            field=models.ForeignKey(blank=True, db_column='questionnaire_session_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transition_history', to='questionnaires.questionnairesession'),
        ),
        migrations.RunPython(
            backfill_questionnaire_session_fk,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='transitionhistory',
            name='uq_hist_inquiry_version',
        ),
        migrations.RemoveConstraint(
            model_name='transitionhistory',
            name='uq_hist_consult_version',
        ),
        migrations.RemoveConstraint(
            model_name='transitionhistory',
            name='uq_hist_visit_version',
        ),
        migrations.RemoveConstraint(
            model_name='transitionhistory',
            name='uq_hist_question_version',
        ),
        migrations.RemoveConstraint(
            model_name='transitionhistory',
            name='ck_hist_target_matches_type',
        ),
        migrations.RenameIndex(
            model_name='transitionhistory',
            new_name='ix_status_inq_event_idem',
            old_name='ix_hist_inquiry_event_idem',
        ),
        migrations.RenameIndex(
            model_name='transitionhistory',
            new_name='ix_status_cons_event_idem',
            old_name='ix_hist_consult_event_idem',
        ),
        migrations.RenameIndex(
            model_name='transitionhistory',
            new_name='ix_status_visit_event_idem',
            old_name='ix_hist_visit_event_idem',
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            restore_questionnaire_session_bridge,
        ),
        migrations.RemoveField(
            model_name='transitionhistory',
            name='questionnaire_session_public_id',
        ),
        migrations.AlterField(
            model_name='transitionhistory',
            name='actor',
            field=models.ForeignKey(blank=True, db_column='changed_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_transitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transitionhistory',
            name='change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transitionhistory',
            name='changed_by_type_code',
            field=models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System')], default='USER', max_length=40),
        ),
        migrations.AlterField(
            model_name='transitionhistory',
            name='event_code',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='transitionhistory',
            name='from_state',
            field=models.CharField(blank=True, db_column='from_status_code', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transitionhistory',
            name='to_state',
            field=models.CharField(db_column='to_status_code', max_length=40),
        ),
        migrations.AddIndex(
            model_name='transitionhistory',
            index=models.Index(condition=models.Q(('target_type_code', 'QUESTIONNAIRE')), fields=['questionnaire_session', 'event_code', 'idempotency_key'], name='ix_status_q_event_idem'),
        ),
        migrations.AddConstraint(
            model_name='transitionhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type_code', 'INQUIRY')), fields=('inquiry', 'state_version'), name='uq_status_history_inquiry_version'),
        ),
        migrations.AddConstraint(
            model_name='transitionhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type_code', 'CONSULTATION')), fields=('consultation', 'state_version'), name='uq_status_history_consultation_version'),
        ),
        migrations.AddConstraint(
            model_name='transitionhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type_code', 'VISIT')), fields=('visit', 'state_version'), name='uq_status_history_visit_version'),
        ),
        migrations.AddConstraint(
            model_name='transitionhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type_code', 'QUESTIONNAIRE')), fields=('questionnaire_session', 'state_version'), name='uq_status_history_questionnaire_version'),
        ),
        migrations.AddConstraint(
            model_name='transitionhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consultation__isnull', True), ('inquiry__isnull', True), ('questionnaire_session__isnull', False), ('target_type_code', 'QUESTIONNAIRE'), ('visit__isnull', True)), models.Q(('consultation__isnull', True), ('inquiry__isnull', False), ('questionnaire_session__isnull', True), ('target_type_code', 'INQUIRY'), ('visit__isnull', True)), models.Q(('consultation__isnull', False), ('inquiry__isnull', True), ('questionnaire_session__isnull', True), ('target_type_code', 'CONSULTATION'), ('visit__isnull', True)), models.Q(('consultation__isnull', True), ('inquiry__isnull', True), ('questionnaire_session__isnull', True), ('target_type_code', 'VISIT'), ('visit__isnull', False)), _connector='OR'), name='ck_status_history_target_type_matches_fk'),
        ),
        migrations.AddConstraint(
            model_name='transitionhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consultation__isnull', True), ('inquiry__isnull', True), ('questionnaire_session__isnull', False), ('visit__isnull', True)), models.Q(('consultation__isnull', True), ('inquiry__isnull', False), ('questionnaire_session__isnull', True), ('visit__isnull', True)), models.Q(('consultation__isnull', False), ('inquiry__isnull', True), ('questionnaire_session__isnull', True), ('visit__isnull', True)), models.Q(('consultation__isnull', True), ('inquiry__isnull', True), ('questionnaire_session__isnull', True), ('visit__isnull', False)), _connector='OR'), name='ck_status_history_exactly_one_target'),
        ),
        migrations.AlterModelTable(
            name='transitionhistory',
            table='support_inquiry_status_history',
        ),
    ]
