# Generated by Django 5.2.16 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_align_contract_status_history"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transitionhistory",
            name="ck_transition_state_version_positive",
        ),
        migrations.RemoveConstraint(
            model_name="transitionhistory",
            name="ck_hist_actor_matches_type",
        ),
        migrations.RemoveConstraint(
            model_name="transitionhistory",
            name="ck_hist_version_origin",
        ),
        migrations.RenameIndex(
            model_name="transitionhistory",
            new_name="ix_status_hist_correlation",
            old_name="ix_transition_correlation",
        ),
        migrations.AddIndex(
            model_name="transitionhistory",
            index=models.Index(
                fields=[
                    "target_type_code",
                    "event_code",
                    "-changed_at",
                ],
                name="ix_status_hist_target_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(state_version__gt=0),
                name="ck_status_history_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        changed_by_type_code="USER",
                        actor__isnull=False,
                    )
                    | models.Q(
                        changed_by_type_code="SYSTEM",
                        actor__isnull=True,
                    )
                ),
                name="ck_status_history_changed_by",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionhistory",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        state_version=1,
                        from_state__isnull=True,
                    )
                    | models.Q(
                        state_version__gt=1,
                        from_state__isnull=False,
                    )
                ),
                name="ck_status_history_version_origin",
            ),
        ),
    ]
