# Generated by Django 5.2.16 on 2026-07-30 08:52

import apps.common_codes.db_expressions
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0004_followup_confirmation'),
        ('subscriptions', '0002_add_synthetic_projection_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_no', models.CharField(max_length=40, unique=True)),
                ('questionnaire_type_code', models.CharField(choices=[('CARE_PRECHECK', 'Care precheck')], default='CARE_PRECHECK', max_length=40)),
                ('status_code', models.CharField(choices=[('UNANSWERED', 'Unanswered'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted')], default='UNANSWERED', max_length=40)),
                ('questionnaire_version', models.CharField(max_length=40)),
                ('answers_payload', models.JSONField(default=dict)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('creation_idempotency_key', models.CharField(max_length=128, unique=True)),
                ('inquiry', models.OneToOneField(blank=True, db_column='inquiry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_session', to='inquiries.inquiry')),
                ('subscription', models.ForeignKey(db_column='subscription_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_sessions', to='subscriptions.customersubscription')),
            ],
            options={
                'db_table': 'support_questionnaire_session',
                'indexes': [models.Index(fields=['subscription', 'status_code', '-created_at'], name='ix_qsession_sub_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('state_version__gt', 0)), name='ck_qsession_state_version'), models.CheckConstraint(condition=apps.common_codes.db_expressions.IsJSONObject(models.F('answers_payload')), name='ck_questionnaire_answers_object'), models.CheckConstraint(condition=models.Q(('questionnaire_type_code__in', ['CARE_PRECHECK'])), name='ck_qsession_type_code'), models.CheckConstraint(condition=models.Q(('status_code__in', ['UNANSWERED', 'IN_PROGRESS', 'SUBMITTED'])), name='ck_qsession_status_code'), models.CheckConstraint(condition=models.Q(models.Q(('status_code__in', ['UNANSWERED', 'IN_PROGRESS']), ('submitted_at__isnull', True)), models.Q(('status_code', 'SUBMITTED'), ('submitted_at__gte', models.F('started_at')), ('submitted_at__isnull', False)), _connector='OR'), name='ck_qsession_submission'), models.CheckConstraint(condition=models.Q(models.Q(('inquiry__isnull', True), ('linked_at__isnull', True)), models.Q(('inquiry__isnull', False), ('linked_at__gte', models.F('submitted_at')), ('linked_at__isnull', False), ('status_code', 'SUBMITTED'), ('submitted_at__isnull', False)), _connector='OR'), name='ck_qsession_inquiry_link')],
            },
        ),
    ]
