"""Inquiry API routes."""

from django.urls import path

from apps.inquiries.api.views import (
    CancelInquiryView,
    ConsultantCustomerSubscriptionSearchView,
    ConsultantInquiryDetailView,
    CreateActionResultView,
    CreateInquiryView,
    CustomerActiveInquiryView,
    CustomerInquiryGuidanceView,
    CustomerInquiryQuestionsView,
    CustomerInquirySnapshotView,
    RegisterConsultantPhoneInquiryView,
    FinalizeInquiryView,
    ReportUnresolvedView,
    RequestConsultationView,
    ResumeConsultationView,
    SubmitResolutionFeedbackView,
    SubmitSymptomView,
    SubmitFollowUpAnswersView,
)


urlpatterns = [
    path(
        "consultant/customer-subscriptions/search",
        ConsultantCustomerSubscriptionSearchView.as_view(),
        name="consultant-customer-subscription-search",
    ),
    path(
        "consultant/phone-inquiries",
        RegisterConsultantPhoneInquiryView.as_view(),
        name="consultant-phone-inquiry-register",
    ),
    path(
        "me/inquiries/active",
        CustomerActiveInquiryView.as_view(),
        name="customer-active-inquiry",
    ),
    path(
        "me/inquiries/<uuid:inquiry_id>",
        CustomerInquirySnapshotView.as_view(),
        name="customer-inquiry-snapshot",
    ),
    path(
        "me/inquiries/<uuid:inquiry_id>/questions",
        CustomerInquiryQuestionsView.as_view(),
        name="customer-inquiry-questions",
    ),
    path(
        "me/inquiries/<uuid:inquiry_id>/guidance",
        CustomerInquiryGuidanceView.as_view(),
        name="customer-inquiry-guidance",
    ),
    path(
        "inquiries",
        CreateInquiryView.as_view(),
        name="inquiry-create",
    ),
    path(
        "inquiries/<uuid:inquiry_id>",
        ConsultantInquiryDetailView.as_view(),
        name="consultant-inquiry-detail",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/cancel",
        CancelInquiryView.as_view(),
        name="inquiry-cancel",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/submit",
        SubmitSymptomView.as_view(),
        name="inquiry-submit",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/answers",
        SubmitFollowUpAnswersView.as_view(),
        name="inquiry-submit-followup-answers",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/action-results",
        CreateActionResultView.as_view(),
        name="inquiry-create-action-result",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/resolution-feedback",
        SubmitResolutionFeedbackView.as_view(),
        name="inquiry-resolution-feedback",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/report-unresolved",
        ReportUnresolvedView.as_view(),
        name="inquiry-report-unresolved",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/resume-consultation",
        ResumeConsultationView.as_view(),
        name="inquiry-resume-consultation",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/finalize",
        FinalizeInquiryView.as_view(),
        name="inquiry-finalize",
    ),
    path(
        "inquiries/<uuid:inquiry_id>/request-consultation",
        RequestConsultationView.as_view(),
        name="inquiry-request-consultation",
    ),
]
