# Generated by Django 5.2.16 on 2026-07-26 07:58

import apps.accounts.models.user
import common.identifiers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.identifiers.generate_user_id, editable=False, max_length=48, primary_key=True, serialize=False, validators=[common.identifiers.validate_domain_id])),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role_code', models.CharField(choices=[('CUSTOMER', '고객'), ('CONSULTANT', '상담사'), ('TECHNICIAN', '방문기사'), ('OPERATOR', '운영자')], max_length=40)),
                ('employee_no', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', apps.accounts.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.CharField(default=common.identifiers.generate_customer_profile_id, editable=False, max_length=48, primary_key=True, serialize=False, validators=[common.identifiers.validate_domain_id])),
                ('customer_no', models.CharField(max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('consent_version', models.CharField(blank=True, max_length=40)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_customer_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_customer_profile',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role_code__in', ['CUSTOMER', 'CONSULTANT', 'TECHNICIAN', 'OPERATOR'])), name='accounts_user_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee_no__isnull', True), ('role_code', 'CUSTOMER')), models.Q(('employee_no__isnull', False), ('role_code__in', ['CONSULTANT', 'TECHNICIAN', 'OPERATOR'])), _connector='OR'), name='accounts_user_employee_by_role'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_synthetic', True)), name='customer_profile_synthetic_only'),
        ),
    ]
