# Generated by Django 5.2.16 on 2026-07-28

import uuid

from django.db import migrations, models


def backfill_public_ids(apps, schema_editor):
    del schema_editor
    for model_name in ("User", "CustomerProfile"):
        model = apps.get_model("accounts", model_name)
        for record in model.objects.filter(public_id__isnull=True).iterator():
            record.public_id = uuid.uuid4()
            record.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="public_id",
            field=models.UUIDField(
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(
            backfill_public_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
