# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inquiries", "0003_add_synthetic_handoff_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "visit_code",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNING", "Assigning"),
                            ("SCHEDULING", "Scheduling"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            (
                                "FOLLOW_UP_REQUIRED",
                                "Follow-up required",
                            ),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ASSIGNING",
                        max_length=40,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "confirmed_cause",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "state_version",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=128),
                ),
                ("correlation_id", models.UUIDField()),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic"),
                            ("operational", "Operational"),
                        ],
                        default="operational",
                        max_length=40,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        db_column="inquiry_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="inquiries.inquiry",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        db_column="technician_id",
                        db_index=False,
                        limit_choices_to={"role_code": "TECHNICIAN"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "field_service_visit",
                "indexes": [
                    models.Index(
                        fields=["inquiry", "-requested_at"],
                        name="ix_visit_inquiry_requested",
                    ),
                    models.Index(
                        fields=["technician", "status"],
                        name="ix_visit_staff_status",
                    ),
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="ix_visit_schedule",
                    ),
                    models.Index(
                        fields=["correlation_id"],
                        name="ix_visit_correlation",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("state_version__gt", 0)),
                        name="ck_visit_state_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "ASSIGNING",
                                    "SCHEDULING",
                                    "CONFIRMED",
                                    "IN_PROGRESS",
                                    "COMPLETED",
                                    "FOLLOW_UP_REQUIRED",
                                    "CANCELLED",
                                ],
                            )
                        ),
                        name="ck_visit_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "data_classification__in",
                                ["synthetic", "operational"],
                            )
                        ),
                        name="ck_visit_data_class",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("idempotency_key", ""),
                            _negated=True,
                        ),
                        name="ck_visit_idempotency_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("started_at__isnull", True),
                                ("status", "ASSIGNING"),
                                ("technician__isnull", True),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("started_at__isnull", True),
                                ("status", "SCHEDULING"),
                                ("technician__isnull", False),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("scheduled_at__isnull", False),
                                ("started_at__isnull", True),
                                ("status", "CONFIRMED"),
                                ("technician__isnull", False),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("started_at__isnull", False),
                                ("status", "IN_PROGRESS"),
                                ("technician__isnull", False),
                            )
                            | models.Q(
                                ("completed_at__isnull", False),
                                ("started_at__isnull", False),
                                (
                                    "status__in",
                                    [
                                        "COMPLETED",
                                        "FOLLOW_UP_REQUIRED",
                                    ],
                                ),
                                ("technician__isnull", False),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("status", "CANCELLED"),
                            )
                        ),
                        name="ck_visit_lifecycle",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("completed_at__isnull", True))
                            | models.Q(
                                (
                                    "completed_at__gte",
                                    models.F("started_at"),
                                )
                            )
                        ),
                        name="ck_visit_complete_order",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("action_taken__isnull", False),
                                ("confirmed_cause__isnull", False),
                                (
                                    "status__in",
                                    [
                                        "COMPLETED",
                                        "FOLLOW_UP_REQUIRED",
                                    ],
                                ),
                            )
                            | (
                                models.Q(
                                    (
                                        "status__in",
                                        [
                                            "COMPLETED",
                                            "FOLLOW_UP_REQUIRED",
                                        ],
                                    ),
                                    _negated=True,
                                )
                                & models.Q(
                                    ("confirmed_cause__isnull", True)
                                )
                                & models.Q(
                                    ("action_taken__isnull", True)
                                )
                            )
                        ),
                        name="ck_visit_result_lifecycle",
                    ),
                ],
            },
        ),
    ]
