# Generated by Django 5.2.16 on 2026-07-30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def add_assigned_technician_fk(_apps, schema_editor):
    """Create the historical composite FK on PostgreSQL."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE "field_service_visit_result"
        ADD CONSTRAINT "fk_visit_result_assigned_technician"
        FOREIGN KEY ("visit_id", "submitted_by_id")
        REFERENCES "field_service_visit" ("id", "technician_id")
        ON DELETE RESTRICT
        """
    )


def remove_assigned_technician_fk(_apps, schema_editor):
    """Remove the PostgreSQL-only composite FK during rollback."""

    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE "field_service_visit_result"
        DROP CONSTRAINT IF EXISTS "fk_visit_result_assigned_technician"
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_promote_integer_primary_keys"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.UniqueConstraint(
                fields=("id", "technician"),
                name="ux_visit_id_technician",
            ),
        ),
        migrations.CreateModel(
            name="VisitResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "cause_category_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                    ),
                ),
                ("inspection_summary", models.TextField()),
                ("action_summary", models.TextField()),
                (
                    "parts_used_text",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "customer_guidance",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "resolved_on_site",
                    models.BooleanField(default=False),
                ),
                (
                    "revisit_required",
                    models.BooleanField(default=False),
                ),
                (
                    "revisit_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "technician_note",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(max_length=128),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                (
                    "next_care_on",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        db_column="submitted_by_id",
                        db_index=False,
                        limit_choices_to={
                            "role_code": "TECHNICIAN"
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_visit_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        db_column="visit_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "db_table": "field_service_visit_result",
                "indexes": [
                    models.Index(
                        fields=[
                            "resolved_on_site",
                            "revisit_required",
                            "completed_at",
                        ],
                        name="ix_visit_result_resolution",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("idempotency_key",),
                        name="ux_visit_result_idempotency",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("revisit_required", False))
                            | models.Q(
                                ("revisit_reason__isnull", False)
                            )
                        ),
                        name="ck_visit_result_revisit_reason",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            add_assigned_technician_fk,
            remove_assigned_technician_fk,
        ),
    ]
