# Generated by Django 5.2.16 on 2026-07-28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "model_code",
                    models.CharField(max_length=60, unique=True),
                ),
                (
                    "model_name",
                    models.CharField(max_length=150),
                ),
                (
                    "generation_code",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        default="SK매직",
                        max_length=100,
                    ),
                ),
                (
                    "launched_on",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "discontinued_on",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "features",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "is_supported_mvp",
                    models.BooleanField(default=False),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
            ],
            options={
                "db_table": "catalog_product_model",
                "indexes": [
                    models.Index(
                        fields=[
                            "is_supported_mvp",
                            "is_active",
                        ],
                        name="ix_product_supported_active",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                discontinued_on__isnull=True
                            )
                            | models.Q(launched_on__isnull=True)
                            | models.Q(
                                discontinued_on__gte=models.F(
                                    "launched_on"
                                )
                            )
                        ),
                        name="ck_product_lifecycle_dates",
                    )
                ],
            },
        ),
    ]
