# Generated by Django 5.2.16 on 2026-07-28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "care_code",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "visit_result_public_id",
                    models.UUIDField(blank=True, null=True),
                ),
                (
                    "care_type_code",
                    models.CharField(
                        choices=[
                            ("FILTER_REPLACEMENT", "필터 교체"),
                            ("PERIODIC_CHECK", "정기 점검"),
                            ("CLEANING", "세척"),
                            ("OTHER", "기타"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        choices=[
                            ("DUE", "예정"),
                            ("SCHEDULED", "예약"),
                            ("COMPLETED", "완료"),
                            ("OVERDUE", "기한 초과"),
                            ("CANCELLED", "취소"),
                        ],
                        default="SCHEDULED",
                        max_length=40,
                    ),
                ),
                ("scheduled_on", models.DateField()),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "source_code",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "고객"),
                            ("CONSULTANT", "상담사"),
                            ("TECHNICIAN", "방문기사"),
                            ("SYSTEM", "시스템"),
                            ("IMPORT", "가져오기"),
                        ],
                        default="SYSTEM",
                        max_length=40,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="performed_by_id",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_care_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        db_column="subscription_id",
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_records",
                        to="subscriptions.customersubscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_care_record",
                "indexes": [
                    models.Index(
                        fields=["subscription", "-completed_at"],
                        name="ix_care_record_subscription",
                    ),
                    models.Index(
                        fields=["status_code", "scheduled_on"],
                        name="ix_care_record_schedule",
                    ),
                    models.Index(
                        fields=["visit_result_public_id"],
                        name="ix_care_record_visit_result",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            care_type_code__in=[
                                "FILTER_REPLACEMENT",
                                "PERIODIC_CHECK",
                                "CLEANING",
                                "OTHER",
                            ]
                        ),
                        name="ck_care_type_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            status_code__in=[
                                "DUE",
                                "SCHEDULED",
                                "COMPLETED",
                                "OVERDUE",
                                "CANCELLED",
                            ]
                        ),
                        name="ck_care_status_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            source_code__in=[
                                "CUSTOMER",
                                "CONSULTANT",
                                "TECHNICIAN",
                                "SYSTEM",
                                "IMPORT",
                            ]
                        ),
                        name="ck_care_source_code",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(status_code="COMPLETED")
                            | (
                                models.Q(completed_at__isnull=False)
                                & models.Q(performed_by__isnull=False)
                                & models.Q(cancelled_at__isnull=True)
                                & models.Q(
                                    cancellation_reason__isnull=True
                                )
                            )
                        ),
                        name="ck_care_completed_state",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(status_code="CANCELLED")
                            | (
                                models.Q(completed_at__isnull=True)
                                & models.Q(performed_by__isnull=True)
                                & models.Q(cancelled_at__isnull=False)
                                & models.Q(
                                    cancellation_reason__isnull=False
                                )
                            )
                        ),
                        name="ck_care_cancelled_state",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(
                                status_code__in=[
                                    "DUE",
                                    "SCHEDULED",
                                    "OVERDUE",
                                ]
                            )
                            | (
                                models.Q(completed_at__isnull=True)
                                & models.Q(performed_by__isnull=True)
                                & models.Q(cancelled_at__isnull=True)
                                & models.Q(
                                    cancellation_reason__isnull=True
                                )
                            )
                        ),
                        name="ck_care_pending_state",
                    ),
                    models.CheckConstraint(
                        condition=~(
                            models.Q(completed_at__isnull=False)
                            & models.Q(cancelled_at__isnull=False)
                        ),
                        name="ck_care_single_outcome",
                    ),
                ],
            },
        ),
    ]
