# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0001_initial"),
        ("inquiries", "0003_add_synthetic_handoff_fields"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="carerecord",
            name="ck_care_type_code",
        ),
        migrations.RemoveConstraint(
            model_name="carerecord",
            name="ck_care_completed_state",
        ),
        migrations.RemoveConstraint(
            model_name="carerecord",
            name="ck_care_cancelled_state",
        ),
        migrations.RemoveConstraint(
            model_name="carerecord",
            name="ck_care_pending_state",
        ),
        migrations.AddField(
            model_name="carerecord",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                db_column="inquiry_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_records",
                to="inquiries.inquiry",
            ),
        ),
        migrations.AddField(
            model_name="carerecord",
            name="performed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carerecord",
            name="result_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NORMAL", "정상"),
                    ("FILTER_REPLACED", "필터 교체 완료"),
                    ("ISSUE_RESOLVED", "문제 해결"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="carerecord",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                db_column="visit_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="care_records",
                to="visits.visit",
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="care_type_code",
            field=models.CharField(
                choices=[
                    ("FILTER_REPLACEMENT", "필터 교체"),
                    ("PERIODIC_CHECK", "정기 점검"),
                    ("CLEANING", "세척"),
                    ("VISIT_SERVICE", "방문 서비스"),
                    ("OTHER", "기타"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="carerecord",
            name="scheduled_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="carerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    care_type_code__in=[
                        "FILTER_REPLACEMENT",
                        "PERIODIC_CHECK",
                        "CLEANING",
                        "VISIT_SERVICE",
                        "OTHER",
                    ]
                ),
                name="ck_care_type_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="carerecord",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(result_code__isnull=True)
                    | models.Q(
                        result_code__in=[
                            "NORMAL",
                            "FILTER_REPLACED",
                            "ISSUE_RESOLVED",
                        ]
                    )
                ),
                name="ck_care_result_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="carerecord",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(status_code="COMPLETED")
                    | (
                        models.Q(cancelled_at__isnull=True)
                        & models.Q(cancellation_reason__isnull=True)
                        & (
                            models.Q(
                                source_code="IMPORT",
                                performed_on__isnull=False,
                                result_code__isnull=False,
                            )
                            | (
                                ~models.Q(source_code="IMPORT")
                                & models.Q(completed_at__isnull=False)
                                & models.Q(performed_by__isnull=False)
                            )
                        )
                    )
                ),
                name="ck_care_completed_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="carerecord",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(status_code="CANCELLED")
                    | (
                        models.Q(completed_at__isnull=True)
                        & models.Q(performed_by__isnull=True)
                        & models.Q(performed_on__isnull=True)
                        & models.Q(result_code__isnull=True)
                        & models.Q(cancelled_at__isnull=False)
                        & models.Q(cancellation_reason__isnull=False)
                    )
                ),
                name="ck_care_cancelled_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="carerecord",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(
                        status_code__in=[
                            "DUE",
                            "SCHEDULED",
                            "OVERDUE",
                        ]
                    )
                    | (
                        models.Q(completed_at__isnull=True)
                        & models.Q(performed_by__isnull=True)
                        & models.Q(performed_on__isnull=True)
                        & models.Q(result_code__isnull=True)
                        & models.Q(cancelled_at__isnull=True)
                        & models.Q(cancellation_reason__isnull=True)
                    )
                ),
                name="ck_care_pending_state",
            ),
        ),
    ]
